// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOkUQsF56l6g0BQHbA2WnHV7ZY1EPfV9w',
    appId: '1:344593376558:web:60810c12dd03c4a9ccc6bf',
    messagingSenderId: '344593376558',
    projectId: 'srl-app-a4109',
    authDomain: 'srl-app-a4109.firebaseapp.com',
    storageBucket: 'srl-app-a4109.firebasestorage.app',
    measurementId: 'G-71HDGSCZZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCkzaH9jvz92-XCJxWGN55eI6xSfsJfhc',
    appId: '1:344593376558:android:d9d88b88124a11cbccc6bf',
    messagingSenderId: '344593376558',
    projectId: 'srl-app-a4109',
    storageBucket: 'srl-app-a4109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsIuv756W2fgzlMZstOvND0IXi3LKxkcA',
    appId: '1:344593376558:ios:a16a30e7ae101f45ccc6bf',
    messagingSenderId: '344593376558',
    projectId: 'srl-app-a4109',
    storageBucket: 'srl-app-a4109.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsIuv756W2fgzlMZstOvND0IXi3LKxkcA',
    appId: '1:344593376558:ios:04b679c2f7f0176fccc6bf',
    messagingSenderId: '344593376558',
    projectId: 'srl-app-a4109',
    storageBucket: 'srl-app-a4109.firebasestorage.app',
    iosBundleId: 'com.masterthesis.srl.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOkUQsF56l6g0BQHbA2WnHV7ZY1EPfV9w',
    appId: '1:344593376558:web:6e7b28797a293548ccc6bf',
    messagingSenderId: '344593376558',
    projectId: 'srl-app-a4109',
    authDomain: 'srl-app-a4109.firebaseapp.com',
    storageBucket: 'srl-app-a4109.firebasestorage.app',
    measurementId: 'G-5RYCQT871X',
  );
}
